[build]
target = "{{ rust_target }}"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "{{ mcu }}"
ESP_IDF_VERSION = "{{ espidfver }}"
ESP_IDF_TOOLS_INSTALL_DIR = "{{ installdir }}"

# Uncomment this if you have moved the target dir by setting CARGO_TARGET_DIR or similar.
# Required for now due to embuild limitations.
#CARGO_WORKSPACE_DIR = { value = "", relative = true }
