[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", ".github", "README.md", "cmake"]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.mcu]
type = "string"
prompt = "Which MCU to target?"
choices = ["esp32", "esp32c2", "esp32c3", "esp32c6", "esp32h2", "esp32s2", "esp32s3"]
default = "esp32"

[placeholders.defaults]
type = "bool"
prompt = "Use the default template values?"
default = true

[conditional.'!defaults'.placeholders.std]
type = "bool"
prompt = "Enable STD support?"
default = true

[conditional.'!defaults && (mcu == "esp32c6" || mcu == "esp32h2")'.placeholders.espidfver]
type = "string"
prompt = "ESP-IDF version (master = UNSTABLE)"
choices = ["master"] # Supported as of v5.1
default = "master"

[conditional.'!defaults && (mcu == "esp32c2")'.placeholders.espidfver]
type = "string"
prompt = "ESP-IDF version (master = UNSTABLE)"
choices = ["v5.1", "master"]
default = "v5.1"

[conditional.'!defaults && (mcu == "esp32" || mcu == "esp32c3" || mcu == "esp32s2" || mcu == "esp32s3")'.placeholders.espidfver]
type = "string"
prompt = "ESP-IDF version (master = UNSTABLE)"
choices = ["v4.4", "v5.1", "master"]
default = "v4.4"

[conditional.'!defaults'.placeholders.devcontainer]
type = "bool"
prompt = "Configure project to use Dev Containers (VS Code and GitHub Codespaces)?"
default = false

[conditional.'!defaults'.placeholders.wokwi]
type = "bool"
prompt = "Configure project to support Wokwi simulation with Wokwi VS Code extension?"
default = false

[conditional.'!std'.placeholders.hal]
type = "string"
prompt = "Include esp-idf-hal/esp-idf-svc?"
choices = ["No", "Yes (default features)", "Yes (all features)"]
default = "Yes (default features)"

[conditional.'!devcontainer']
ignore = [
    ".devcontainer/",
    ".vscode/tasks.json",
    ".dockerignore",
    "docs/",
    "scripts/",
]

[conditional.'!wokwi']
ignore = [".vscode/launch.json", "diagram.json", "wokwi.toml"]

[conditional.'defaults']
ignore = [
    ".devcontainer/",
    ".vscode/",
    "docs/",
    "scripts/",
    ".dockerignore",
    "diagram.json",
    "wokwi.toml",
]
