[template]
cargo_generate_version = ">=0.17.4"
ignore = [".git", ".github", "README.md", "cmake"]

[hooks]
pre = ["pre-script.rhai"]

[placeholders.mcu]
type = "string"
prompt = "Which MCU to target?"
choices = ["esp32", "esp32c3", "esp32s2", "esp32s3", "esp32c6", "esp32c2", "esp32h2", "esp32p4"]
default = "esp32"

[placeholders.defaults]
type = "bool"
prompt = "Use the default template values?"
default = true

[conditional.'defaults == false'.placeholders.std]
type = "bool"
prompt = "Enable STD support?"
default = true

[conditional.'defaults == false'.placeholders.espidfver]
type = "string"
prompt = "ESP-IDF version (master = UNSTABLE)"
choices = ["v4.4", "v5.0", "master"]
default = "v4.4"

[conditional.'defaults == false'.placeholders.devcontainer]
type = "bool"
prompt = "Configure project to use Dev Containers (VS Code and GitHub Codespaces)?"
default = false

[conditional.'defaults == false'.placeholders.wokwi]
type = "bool"
prompt = "Configure project to support Wokwi simulation with Wokwi VS Code extension?"
default = false

[conditional.'std == true'.placeholders.hal]
type = "string"
prompt = "Include esp-idf-hal/esp-idf-svc?"
choices = ["No", "Yes (default features)", "Yes (all features)"]
default = "Yes (default features)"

[conditional.'devcontainer == false']
ignore = [
    ".devcontainer/",
    ".vscode/tasks.json",
    ".dockerignore",
    "docs/",
    "scripts/",
]

[conditional.'wokwi == false']
ignore = [".vscode/launch.json", "diagram.json", "wokwi.toml"]

[conditional.'defaults == true']
ignore = [
    ".devcontainer/",
    ".vscode/",
    "docs/",
    "scripts/",
    ".dockerignore",
    "diagram.json",
    "wokwi.toml",
]
