[template]
cargo_generate_version = ">=0.17.4"

[placeholders.toolchain]
type = "string"
prompt = "Rust toolchain (beware: nightly works only for riscv MCUs!)"
choices = ["esp", "nightly"]
default = "esp"
